import dotenv from "dotenv";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

export const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
export const sourcePath = resolve(root, ".env.local");

export const GENERATED_ENV_HEADER = "# Generated by npm run dev:env. Do not edit directly.";

export const serviceEnvKeys = {
  web: [
    "GITHUB_CLIENT_ID",
    "GITHUB_CLIENT_SECRET",
    "NEXTAUTH_URL",
    "NEXTAUTH_SECRET",
    "CONTROL_PLANE_URL",
    "NEXT_PUBLIC_WS_URL",
    "NEXT_PUBLIC_SANDBOX_PROVIDER",
    "NEXT_PUBLIC_SCM_PROVIDER",
    "INTERNAL_CALLBACK_SECRET",
    "ALLOWED_USERS",
    "ALLOWED_EMAIL_DOMAINS",
    "UNSAFE_ALLOW_ALL_USERS",
  ],
  controlPlane: [
    "GITHUB_CLIENT_ID",
    "GITHUB_CLIENT_SECRET",
    "TOKEN_ENCRYPTION_KEY",
    "REPO_SECRETS_ENCRYPTION_KEY",
    "INTERNAL_CALLBACK_SECRET",
    "GITHUB_APP_ID",
    "GITHUB_APP_PRIVATE_KEY",
    "GITHUB_APP_INSTALLATION_ID",
    "MODAL_TOKEN_ID",
    "MODAL_TOKEN_SECRET",
    "MODAL_API_SECRET",
    "MODAL_WORKSPACE",
    "DAYTONA_API_KEY",
    "DAYTONA_API_URL",
    "DAYTONA_BASE_SNAPSHOT",
    "DEPLOYMENT_NAME",
    "SCM_PROVIDER",
    "SANDBOX_PROVIDER",
    "WORKER_URL",
    "WEB_APP_URL",
    "LOG_LEVEL",
  ],
  modalSecrets: [
    "ANTHROPIC_API_KEY",
    "GITHUB_APP_ID",
    "GITHUB_APP_PRIVATE_KEY",
    "GITHUB_APP_INSTALLATION_ID",
    "MODAL_API_SECRET",
    "INTERNAL_CALLBACK_SECRET",
    "CONTROL_PLANE_URL",
  ],
};

export const requiredEnvKeys = {
  web: [
    "GITHUB_CLIENT_ID",
    "GITHUB_CLIENT_SECRET",
    "NEXTAUTH_URL",
    "NEXTAUTH_SECRET",
    "CONTROL_PLANE_URL",
    "NEXT_PUBLIC_WS_URL",
    "INTERNAL_CALLBACK_SECRET",
  ],
  controlPlane: [
    "GITHUB_CLIENT_ID",
    "GITHUB_CLIENT_SECRET",
    "TOKEN_ENCRYPTION_KEY",
    "REPO_SECRETS_ENCRYPTION_KEY",
    "INTERNAL_CALLBACK_SECRET",
    "GITHUB_APP_ID",
    "GITHUB_APP_PRIVATE_KEY",
    "GITHUB_APP_INSTALLATION_ID",
    "DEPLOYMENT_NAME",
    "WORKER_URL",
    "WEB_APP_URL",
  ],
};

const modalControlPlaneKeys = [
  "MODAL_TOKEN_ID",
  "MODAL_TOKEN_SECRET",
  "MODAL_API_SECRET",
  "MODAL_WORKSPACE",
];

const daytonaControlPlaneKeys = ["DAYTONA_API_KEY", "DAYTONA_API_URL", "DAYTONA_BASE_SNAPSHOT"];

export function getRequiredEnvKeys(env) {
  const sandboxProvider = normalizeProvider(env.SANDBOX_PROVIDER, "modal");

  if (sandboxProvider === "modal") {
    return {
      ...requiredEnvKeys,
      controlPlane: [...requiredEnvKeys.controlPlane, ...modalControlPlaneKeys],
      modalSecrets: serviceEnvKeys.modalSecrets,
    };
  }

  if (sandboxProvider === "daytona") {
    return {
      ...requiredEnvKeys,
      controlPlane: [...requiredEnvKeys.controlPlane, ...daytonaControlPlaneKeys],
      modalSecrets: [],
    };
  }

  console.error(`Unsupported SANDBOX_PROVIDER in .env.local: ${env.SANDBOX_PROVIDER}`);
  process.exit(1);
}

function normalizeProvider(value, defaultValue) {
  return value?.trim().toLowerCase() || defaultValue;
}

export function readRootEnv() {
  let source;
  try {
    source = readFileSync(sourcePath, "utf8");
  } catch {
    console.error("Missing .env.local. Copy .env.example to .env.local and fill in real values.");
    process.exit(1);
  }

  return withDerivedEnv(normalizeEnv(dotenv.parse(source)));
}

export function normalizeEnv(env) {
  return Object.fromEntries(
    Object.entries(env).map(([key, value]) => [key, value.replace(/\\n/g, "\n")])
  );
}

export function withDerivedEnv(env) {
  return {
    ...env,
    NEXT_PUBLIC_SANDBOX_PROVIDER: env.NEXT_PUBLIC_SANDBOX_PROVIDER || env.SANDBOX_PROVIDER,
    NEXT_PUBLIC_SCM_PROVIDER: env.NEXT_PUBLIC_SCM_PROVIDER || env.SCM_PROVIDER,
  };
}

export function requireEnv(env, keys, context = ".env.local") {
  const missing = [...new Set(keys)].filter((key) => !env[key]);
  if (missing.length > 0) {
    console.error(`Missing required values in ${context}: ${missing.join(", ")}`);
    process.exit(1);
  }
}

export function serializeEnv(env, keys) {
  return `${GENERATED_ENV_HEADER}\n${keys
    .map((key) => {
      const value = env[key] ?? "";
      const serialized = value.includes("\n") ? JSON.stringify(value) : value;
      return `${key}=${serialized}`;
    })
    .join("\n")}\n`;
}

export function writeEnv(path, contents) {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, contents);
  console.log(`wrote ${path.replace(`${root}/`, "")}`);
}
